// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using LuaInterface;
using UnityEngine.UI;

//[RequireComponent(typeof(LuaComponent))]
public class LuaExtensionComponent : MonoBehaviour
{
	protected LuaTable luaBehaviour = null;

	public virtual void OnLuaBehaviourInitalized(LuaTable luaB){
		luaBehaviour = luaB;
	}
}

